# Generated by Django 5.2.17 on 2026-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('organization', 'Organization'), ('competition', 'Competition'), ('teaching', 'Teaching'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('internship', 'Internship')], default='organization', max_length=20),
        ),
    ]
