# Generated by Django 5.2.17 on 2026-09-12 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('meta', models.CharField(help_text='Contoh: Perempuan Inovasi 2025 Bootcamp · June 2025', max_length=255)),
                ('description', models.TextField()),
                ('tags', models.CharField(help_text='Pisahkan dengan koma, contoh: HTML, CSS, JavaScript', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Angka lebih kecil tampil lebih dulu')),
            ],
        ),
    ]
