# Generated by Django 5.2.17 on 2026-09-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experience_starred_by_project_starred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='starred_by',
        ),
    ]
