# Generated by Django 5.2.17 on 2026-09-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_experience_starred_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPhoto',
        ),
    ]
