# Generated by Django 5.2.17 on 2026-09-26 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_galleryphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Songfess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Nama yang ingin ditampilkan', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Cerita singkat / mood pengirim')),
                ('song_title', models.CharField(blank=True, help_text='Diisi oleh pemilik portofolio', max_length=255)),
                ('song_url', models.URLField(blank=True, help_text='Link Spotify/YouTube (opsional)')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='songfess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
