# Generated by Django 5.2.17 on 2026-09-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_songfess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songfess',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='songfess',
            name='replied_at',
        ),
    ]
